version: '2'
services:
  socks-app:
    image: 'wallet:latest'
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-app
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: my_wallet

  postgres:
    image: 'postgres:latest'
    container_name: postgres-wallet-app
    ports:
      - "5432:5432"
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'